/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "add.h"

bool_t
xdr_paper(xdrs, objp)
	XDR *xdrs;
	paper *objp;
{

	if (!xdr_long(xdrs, &objp->len))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->val, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_str_add(xdrs, objp)
	XDR *xdrs;
	str_add *objp;
{

	if (!xdr_string(xdrs, &objp->name, ~0))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->title, ~0))
		return (FALSE);
	if (!xdr_paper(xdrs, &objp->p))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_str_list(xdrs, objp)
	XDR *xdrs;
	str_list *objp;
{

	if (!xdr_int(xdrs, &objp->number))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->name, ~0))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->title, ~0))
		return (FALSE);
	if (!xdr_pointer(xdrs, (char **)&objp->next, sizeof(str_list), (xdrproc_t)xdr_str_list))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_str_info(xdrs, objp)
	XDR *xdrs;
	str_info *objp;
{

	if (!xdr_int(xdrs, &objp->number))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->name, ~0))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->title, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_int_out(xdrs, objp)
	XDR *xdrs;
	int_out *objp;
{

	if (!xdr_int(xdrs, objp))
		return (FALSE);
	return (TRUE);
}
