/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "add.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

int_out *
add_1(argp, clnt)
	str_add *argp;
	CLIENT *clnt;
{
	static int_out clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, ADD, xdr_str_add, argp, xdr_int_out, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

int_out *
remove_1(argp, clnt)
	int *argp;
	CLIENT *clnt;
{
	static int_out clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, REMOVE, xdr_int, argp, xdr_int_out, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

str_list *
list_1(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static str_list clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, LIST, xdr_void, argp, xdr_str_list, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

str_info *
info_1(argp, clnt)
	int *argp;
	CLIENT *clnt;
{
	static str_info clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, INFO, xdr_int, argp, xdr_str_info, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

paper *
fetch_1(argp, clnt)
	int *argp;
	CLIENT *clnt;
{
	static paper clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, FETCH, xdr_int, argp, xdr_paper, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}
