


all:
	# call all Makefiles in the subdirectories
	make -s -C hotel
	make -s -C hotelgw
	make -s -C hotelgwclient
	make -s -C paper

clean:
	make -C hotel clean
	make -C hotelgw clean
	make -C hotelgwclient clean
	make -C paper clean
