


# just call all Makefiles in the subdirectories
all:
	make -C hotel
	make -C hotelgw
	make -C hotelgwclient
	make -C paper

clean:
	make -C hotel clean
	make -C hotelgw clean
	make -C hotelgwclient clean
	make -C paper clean
