/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ADD_H_RPCGEN
#define _ADD_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct param {
	char *arg;
	struct param *next;
};
typedef struct param param;
#ifdef __cplusplus
extern "C" bool_t xdr_param(XDR *, param*);
#elif __STDC__
extern  bool_t xdr_param(XDR *, param*);
#else /* Old Style C */
bool_t xdr_param();
#endif /* Old Style C */


typedef int add_out;
#ifdef __cplusplus
extern "C" bool_t xdr_add_out(XDR *, add_out*);
#elif __STDC__
extern  bool_t xdr_add_out(XDR *, add_out*);
#else /* Old Style C */
bool_t xdr_add_out();
#endif /* Old Style C */


#define ADD_PROG ((rpc_uint)0x20001234)
#define ADD_VERS ((rpc_uint)1)

#ifdef __cplusplus
#define ADD ((rpc_uint)1)
extern "C" add_out * add_1(param *, CLIENT *);
extern "C" add_out * add_1_svc(param *, struct svc_req *);

#elif __STDC__
#define ADD ((rpc_uint)1)
extern  add_out * add_1(param *, CLIENT *);
extern  add_out * add_1_svc(param *, struct svc_req *);

#else /* Old Style C */
#define ADD ((rpc_uint)1)
extern  add_out * add_1();
extern  add_out * add_1_svc();
#endif /* Old Style C */

#endif /* !_ADD_H_RPCGEN */
