/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "add.h"

bool_t
xdr_param(xdrs, objp)
	XDR *xdrs;
	param *objp;
{

	if (!xdr_string(xdrs, &objp->arg, 32))
		return (FALSE);
	if (!xdr_pointer(xdrs, (char **)&objp->next, sizeof(param), (xdrproc_t)xdr_param))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_add_out(xdrs, objp)
	XDR *xdrs;
	add_out *objp;
{

	if (!xdr_int(xdrs, objp))
		return (FALSE);
	return (TRUE);
}
