#!all: Hotel HotelImp HotelServer HotelClient
all:
	javac Hotel.java
	javac HotelImp.java
	javac HotelServer.java
	javac HotelClient.java

#!Hotel: Hotel.java
#!	javac Hotel.java

#!HotelImp: HotelImp.java
#!	javac HotelImp.java

#!HotelServer: HotelServer.java
#!	javac HotelServer.java

#!HotelClient: HotelClient.java
#!	javac HotelClient.java

clean:
	rm *.class

#!.PHONY: hotel hotelimp hotelserver hotelclient
