/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "paper.h"

bool_t
xdr_paper (XDR *xdrs, paper *objp)
{
	register int32_t *buf;

	 if (!xdr_long (xdrs, &objp->len))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->val, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_str_add (XDR *xdrs, str_add *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->name, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->title, ~0))
		 return FALSE;
	 if (!xdr_paper (xdrs, &objp->p))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_str_list (XDR *xdrs, str_list *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->number))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->name, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->title, ~0))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (str_list), (xdrproc_t) xdr_str_list))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_str_info (XDR *xdrs, str_info *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->number))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->name, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->title, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_int_out (XDR *xdrs, int_out *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, objp))
		 return FALSE;
	return TRUE;
}
