/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PAPER_H_RPCGEN
#define _PAPER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct paper {
	long len;
	char *val;
};
typedef struct paper paper;

struct str_add {
	char *name;
	char *title;
	struct paper p;
};
typedef struct str_add str_add;

struct str_list {
	int number;
	char *name;
	char *title;
	struct str_list *next;
};
typedef struct str_list str_list;

struct str_info {
	int number;
	char *name;
	char *title;
};
typedef struct str_info str_info;

typedef int int_out;

#define PAPER_SERVER 0x20002345
#define PAPER_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADD 1
extern  int_out * add_1(str_add *, CLIENT *);
extern  int_out * add_1_svc(str_add *, struct svc_req *);
#define REMOVE 2
extern  int_out * remove_1(int *, CLIENT *);
extern  int_out * remove_1_svc(int *, struct svc_req *);
#define LIST 3
extern  str_list * list_1(void *, CLIENT *);
extern  str_list * list_1_svc(void *, struct svc_req *);
#define INFO 4
extern  str_info * info_1(int *, CLIENT *);
extern  str_info * info_1_svc(int *, struct svc_req *);
#define FETCH 5
extern  paper * fetch_1(int *, CLIENT *);
extern  paper * fetch_1_svc(int *, struct svc_req *);
extern int paper_server_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD 1
extern  int_out * add_1();
extern  int_out * add_1_svc();
#define REMOVE 2
extern  int_out * remove_1();
extern  int_out * remove_1_svc();
#define LIST 3
extern  str_list * list_1();
extern  str_list * list_1_svc();
#define INFO 4
extern  str_info * info_1();
extern  str_info * info_1_svc();
#define FETCH 5
extern  paper * fetch_1();
extern  paper * fetch_1_svc();
extern int paper_server_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_paper (XDR *, paper*);
extern  bool_t xdr_str_add (XDR *, str_add*);
extern  bool_t xdr_str_list (XDR *, str_list*);
extern  bool_t xdr_str_info (XDR *, str_info*);
extern  bool_t xdr_int_out (XDR *, int_out*);

#else /* K&R C */
extern bool_t xdr_paper ();
extern bool_t xdr_str_add ();
extern bool_t xdr_str_list ();
extern bool_t xdr_str_info ();
extern bool_t xdr_int_out ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PAPER_H_RPCGEN */
