all: hotel hotelimp hotelserver hotelclient

hotel: Hotel.java
	javac Hotel.java

hotelimp: HotelImp.java
	javac HotelImp.java

hotelserver: HotelServer.java
	javac HotelServer.java

hotelclient: HotelClient.java
	javac HotelClient.java

clean:
	rm *.class
