all: Hotel HotelImp HotelServer HotelClient

Hotel: Hotel.java
	javac Hotel.java

HotelImp: HotelImp.java
	javac HotelImp.java

HotelServer: HotelServer.java
	javac HotelServer.java

HotelClient: HotelClient.java
	javac HotelClient.java

clean:
	rm *.class

.PHONY: hotel hotelimp hotelserver hotelclient
